#!/bin/sh -e

OLDPATH=$PATH; PATH=".:..:$(dirname $0):$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

UA='Mozilla/5.0 (Linux; U; Android 2.2; en-us; Desire_A8181 Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1'

MONITOR_REQS=(
	"URL=https://ihelper.mts.ru/SELFCAREPDA/Security.mvc/LogOn?returnLink=http%3A%2F%2Fihelper.mts.ru%3A8083%2FSELFCAREPDA%2FHome.mvc"
	"URL=https://ihelper.mts.ru/SELFCAREPDA/Security.mvc/LogOn?returnLink=http%3A%2F%2Fihelper.mts.ru%3A8083%2FSELFCAREPDA%2FHome.mvc ARGS=--post-data=username=$LOGIN&password=$PASSWORD"
)

findstring()
{
	# <br/>Баланс: <strong><strong>123.45</strong> руб.</strong>
	echo "$(sed -ne '/<br\/>Баланс:/ { s,.*>\([0-9.]*\)</.*$,\1,; p; }' <$1)"
}

monitor
